language: node_js

node_js:
  - node

dist: trusty
sudo: false

env:
  global:
    secure: C0jlgExCOgzzbu9gJwGLIxyZqVWhMqxoGo90BkrF1JN317ysMOjKYz3ThiQh7d4EbYSDpR7u2TJl3TGFR2qKfBjfDRSpCW3bjdn07eBPo92FtbTmOG1rHriPNgvLJcCzO6WiB92wAlupi0TJP6KW0y5IvAYwxF3q2vSzEDlAZF5kghNQBhxu9fkXcHQDbCpEe1caA01UUd3DAplbrvOlkY1rK+ClGDCK2fkFuPc6A9Vjg/KQavtOX6xr2PeFNHs4Ge9G2XGpjY/sjOW01j/BmzdPSIh3F4qLy1u/NutUXZ+UyjNF2M2UY7htYRTSokGsTxX5SAmSxsT8s4c5+ZjVKUbbGSvK/sYt/AJacCnxYrutkbB7T72dnhXXqDP2EzXcpRKISDesiAfb6TUoayiGGutGyAYBWHvvBTMq6qxMCZ14HvCKzG7ELiw1SwZHyEhCN/lG8dBlJ4whpSkfhFJN64brW2N6ThGCt/LiIHOgGg3LHz2jDBsPub66D1LRWxvNR71Bw9vT8g07KGM3TLsy+PSs2EdVeKWv29uD5/5iI+oVcFcscxMIB0UPXQitJ6GdNyvyzsfO+pysLA/gBLxnSWyX/kHXS/VwwpHSys0gYaEUevSlhjSo+KjJMO3ltjV6NFTMWzX1syqM36vSzxtIcc03lTdwU0blJR61rdlyoxs=

addons:
  ssh_known_hosts: gendercomics.net

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_c82131f2301a_key -iv $encrypted_c82131f2301a_iv -in deploy-key.enc -out deploy-key -d

before_script:
  - VERSION=$(node -p -e "require('./package.json').version")

stages:
  - build-stage
  - name: build-production
    if: branch = master

jobs:
  include:
    # build-stage
    - stage: build-stage
    - script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f Dockerfile-stage -t gendercomics/admin-webapp-stage .
      - docker tag gendercomics/admin-webapp-stage gendercomics/admin-webapp-stage:latest
      - docker images
      - docker push gendercomics/admin-webapp-stage:latest
    # build-production
    - stage: build-production
    - script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t gendercomics/admin-webapp .
      - docker tag gendercomics/admin-webapp gendercomics/admin-webapp:latest
      - docker tag gendercomics/admin-webapp gendercomics/admin-webapp:$VERSION
      - docker images
      - docker push gendercomics/admin-webapp:latest
      - docker push gendercomics/admin-webapp:$VERSION

before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add deploy-key
  - scp -r ./docker-compose.yml deploy@gendercomics.net:/var/gendercomics/admin-webapp
  - scp -r ./docker-compose.yml deploy@gendercomics.net:/var/gendercomics/admin-webapp-stage

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh deploy@gendercomics.net 'docker pull gendercomics/admin-webapp-stage:latest && cd /var/gendercomics/admin-webapp-stage && docker-compose up -d gendercomics-admin-webapp-stage'
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: ssh deploy@gendercomics.net 'docker pull gendercomics/admin-webapp:$VERSION && cd /var/gendercomics/admin-webapp && docker-compose up -d gendercomics-admin-webapp'
    on:
      branch: master

notifications:
  slack:
    rooms:
     - visualitiesofgender:3zAI6z6JJXLeEIaBU49O0Wkr#builds
    on_success: change
  email:
    recipients:
      - michael.litschauer@gmail.com
    on_success: change
    on_failure: always

