version: '3'

services:

  gendercomics-admin-webapp-stage:
    image: gendercomics/admin-webapp:latest
    container_name: gendercomics-admin-webapp-stage
    networks:
      - proxy
    labels:
      - "traefik.frontend.rule=Host:stage.${HOST}; PathPrefixStrip: /admin"
      - "traefik.port=80"
      - "traefik.frontend.auth.basic=gesche:$$apr1$$MAPCYH7m$$8wTgBxTOH731kXK3fo1JC/"

networks:
  proxy:
    external: true
