allowBuilds:
  '@fortawesome/fontawesome-common-types': true
  '@fortawesome/fontawesome-svg-core': true
  '@fortawesome/free-regular-svg-icons': true
  '@fortawesome/free-solid-svg-icons': true
  '@parcel/watcher': true
  bootstrap-vue: true
  core-js: true
  deasync: false
  ejs: true
  node-sass: true
  yorkie: true
